export default {
  logo: require('../assets/images/logo.png'),
  eye: require('../assets/images/eye.png'),
  home: require('../assets/images/home.png'),
  home: require('../assets/images/home.png'),
  contact: require('../assets/images/contact.png'),
  dashbord: require('../assets/images/dashbord.png'),
  profile: require('../assets/images/profile.png'),
  homeActive: require('../assets/images/homeActive.png'),
  dashboardActive: require('../assets/images/dashboardActive.png'),
  contactActive: require('../assets/images/contactActive.png'),
  profileActive: require('../assets/images/profileActive.png'),
  welcomeLogo: require('../assets/images/welcomeLogo.png'),
  trash: require('../assets/images/trash.png'),
  edit: require('../assets/images/edit.png'),
  changePass: require('../assets/images/changePass.png'),
  setting: require('../assets/images/setting.png'),
  aboutUs: require('../assets/images/aboutUs.png'),
  contactUs: require('../assets/images/contactUs.png'),
  termsAndCondition: require('../assets/images/termsAndCondition.png'),
  privacy: require('../assets/images/privacy.png'),
  logout: require('../assets/images/logout.png'),
  arrowRight: require('../assets/images/arrowRight.png'),
  backIcon: require('../assets/images/backIcon.png'),
  dp: require('../assets/images/dp.png'),
  camara: require('../assets/images/camara.png'),
  appLogo: require('../assets/images/appLogo.png'),
  copyright: require('../assets/images/copyright.png'),
  downArrow: require('../assets/images/downArrow.png'),
  closeEye: require('../assets/images/closeEye.png'),
  
};
